from google.cloud import storage, bigquery
base_url = "https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports_us/"

# Cloud storage
storage_client = storage.Client.from_service_account_json('creds.json')
bucket_name = 'final_proejct'
bucket = storage_client.bucket(bucket_name)

# Big Query
bigquery_client = bigquery.Client.from_service_account_json('creds.json')

PROJECT = 'basic-lock-401321'
CREATE_COVID_TABLES = f"""
CREATE SCHEMA IF NOT EXISTS RAW;

CREATE TABLE IF NOT EXISTS RAW.COVID (
    PROVINCE_STATE STRING,
    COUNTRY_REGION STRING,
    LAST_UPDATE TIMESTAMP,
    LAT FLOAT64,
    LONG_ FLOAT64,
    CONFIRMED INT,
    DEATHS INT,
    RECOVERED FLOAT64,
    ACTIVE FLOAT64,
    FIPS FLOAT64,
    INCIDENT_RATE FLOAT64,
    TOTAL_TEST_RESULTS FLOAT64,
    PEOPLE_HOSPITALIZED STRING,
    CASE_FATALITY_RATIO FLOAT64,
    UID FLOAT64,
    ISO3 STRING,
    TESTING_RATE FLOAT64,
    HOSPITALIZATION_RATE STRING,
    DATE DATE,
    PEOPLE_TESTED STRING,
    MORTALITY_RATE STRING
);
"""

MERGE_COVID_TABLES = f"""
MERGE INTO RAW.COVID
USING RAW.STG_COVID
ON RAW.COVID.PROVINCE_STATE = RAW.STG_COVID.PROVINCE_STATE
AND RAW.COVID.LAST_UPDATE = RAW.STG_COVID.LAST_UPDATE

WHEN NOT MATCHED THEN INSERT (
    PROVINCE_STATE,
    COUNTRY_REGION,
    LAST_UPDATE,
    LAT,
    LONG_,
    CONFIRMED,
    DEATHS,
    RECOVERED,
    ACTIVE,
    FIPS,
    INCIDENT_RATE,
    TOTAL_TEST_RESULTS,
    PEOPLE_HOSPITALIZED,
    CASE_FATALITY_RATIO,
    UID,
    ISO3,
    TESTING_RATE,
    HOSPITALIZATION_RATE,
    DATE,
    PEOPLE_TESTED,
    MORTALITY_RATE
)

VALUES (
    RAW.STG_COVID.PROVINCE_STATE,
    RAW.STG_COVID.COUNTRY_REGION,
    RAW.STG_COVID.LAST_UPDATE,
    RAW.STG_COVID.LAT,
    RAW.STG_COVID.LONG_,
    RAW.STG_COVID.CONFIRMED,
    RAW.STG_COVID.DEATHS,
    RAW.STG_COVID.RECOVERED,
    RAW.STG_COVID.ACTIVE,
    RAW.STG_COVID.FIPS,
    RAW.STG_COVID.INCIDENT_RATE,
    RAW.STG_COVID.TOTAL_TEST_RESULTS,
    RAW.STG_COVID.PEOPLE_HOSPITALIZED,
    RAW.STG_COVID.CASE_FATALITY_RATIO,
    RAW.STG_COVID.UID,
    RAW.STG_COVID.ISO3,
    RAW.STG_COVID.TESTING_RATE,
    RAW.STG_COVID.HOSPITALIZATION_RATE,
    RAW.STG_COVID.DATE,
    RAW.STG_COVID.PEOPLE_TESTED,
    RAW.STG_COVID.MORTALITY_RATE
)

WHEN MATCHED THEN UPDATE SET
    PROVINCE_STATE = RAW.STG_COVID.PROVINCE_STATE,
    COUNTRY_REGION = RAW.STG_COVID.COUNTRY_REGION,
    LAST_UPDATE = RAW.STG_COVID.LAST_UPDATE,
    LAT = RAW.STG_COVID.LAT,
    LONG_ = RAW.STG_COVID.LONG_,
    CONFIRMED = RAW.STG_COVID.CONFIRMED,
    DEATHS = RAW.STG_COVID.DEATHS,
    RECOVERED = RAW.STG_COVID.RECOVERED,
    ACTIVE = RAW.STG_COVID.ACTIVE,
    FIPS = RAW.STG_COVID.FIPS,
    INCIDENT_RATE = RAW.STG_COVID.INCIDENT_RATE,
    TOTAL_TEST_RESULTS = RAW.STG_COVID.TOTAL_TEST_RESULTS,
    PEOPLE_HOSPITALIZED = RAW.STG_COVID.PEOPLE_HOSPITALIZED,
    CASE_FATALITY_RATIO = RAW.STG_COVID.CASE_FATALITY_RATIO,
    UID = RAW.STG_COVID.UID,
    ISO3 = RAW.STG_COVID.ISO3,
    TESTING_RATE = RAW.STG_COVID.TESTING_RATE,
    HOSPITALIZATION_RATE,
    DATE = RAW.STG_COVID.DATE,
    PEOPLE_TESTED = RAW.STG_COVID.PEOPLE_TESTED,
    MORTALITY_RATE = RAW.STG_COVID.MORTALITY_RATE
"""

TABLE_ID = f'{PROJECT}.RAW.COVID'

DATA_COLUMNS = [
    'Province_State',
    'Country_Region',
    'Last_Update',
    'Lat',
    'Long_',
    'Confirmed',
    'Deaths',
    'Recovered',
    'Active',
    'Fips',
    'Incident_Rate',
    'Total_Test_Results',
    'People_Hospitalized',
    'Case_Fatality_Ratio',
    'UID',
    'ISO3',
    'Testing_Rate',
    'Hospitalization_Rate',
    'Date',
    'People_Tested',
    'Mortality_Rate']